# Generated by Django 5.1.3 on 2024-12-02 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=11, null=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال ؟')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='شماره تلفن')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('code', models.SmallIntegerField(verbose_name='کد ارسال شده')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='توکن')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تلفن')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('postal_code', models.PositiveSmallIntegerField(verbose_name='کد پستی')),
                ('text', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='یوزر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
