# Generated by Django 5.1.3 on 2024-12-02 19:35

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountCaffeine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='میزان کافئین')),
            ],
            options={
                'verbose_name_plural': 'میزان کافئین',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.category', verbose_name='دسته بندی های دیگر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان محصول')),
                ('image1', models.ImageField(upload_to='', verbose_name='عکس اول')),
                ('image2', models.ImageField(null=True, upload_to='', verbose_name='عکس دوم')),
                ('image3', models.ImageField(null=True, upload_to='', verbose_name='عکس سوم')),
                ('image4', models.ImageField(null=True, upload_to='', verbose_name='عکس چهارم')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('discount', models.SmallIntegerField(verbose_name='تخفیف')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='خاستگاه')),
                ('ingredient', models.CharField(blank=True, max_length=200, null=True, verbose_name='ماده تشکیل دهنده')),
                ('introduction', models.TextField(verbose_name='مقدمه')),
                ('best_selling', models.BooleanField(default=False, verbose_name='بهترین فروش')),
                ('amazing', models.BooleanField(default=False, verbose_name='محصولات شگفت انگیز')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ثبت محصول')),
                ('amountcaffeine', models.ManyToManyField(to='product.amountcaffeine', verbose_name='میزان کافئین')),
                ('category', models.ManyToManyField(to='product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کامنت محصول',
                'verbose_name_plural': 'کامنت محصولات',
            },
        ),
    ]
