# Generated by Django 5.1.3 on 2025-03-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ingredient',
            field=models.TextField(blank=True, null=True, verbose_name='مواد لازم'),
        ),
        migrations.AlterField(
            model_name='article',
            name='recipe',
            field=models.TextField(blank=True, null=True, verbose_name='رسپی'),
        ),
    ]
