# Generated by Django 5.1.3 on 2025-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'پرداخت'), ('Processing', 'در حال پردازش'), ('Shipped', 'در حال ارسال'), ('Delivered', 'تحویل داده شده')], default='Pending', max_length=100),
        ),
    ]
